### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SergiuCip** [cgalvarez/puppet-mariadb#1]
Hi there,

When I am trying to use your module on CentOs I get an error saying that the version doesn't match so I have hard code it. 

After doing so, I've tried running Puppet again and I've stumbled upon another error which is: Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at '.'; expected '}' at /etc/puppetlabs/puppet/modules/mariadb/manifests/repo.pp:75 on node learning.puppetlabs.vm

Could you please have a look and let me know what I am doing wrong?

I am using Puppet 3.7 on CentOs 6

Thank you,

Kind regards,
Sergiu

**Comment by cgalvarez** [comment]
Hi, Sergiu.

Sincerily, I have only tested it on Ubuntu. I will make some tests to see what's happening. Please, attach your manifest to exactly reproduce your case.

Thank you in advance for giving my module a try and providing your feedback.

**Comment by cgalvarez** [comment]
Sergiu, I've commited a fix for the bug occurring when the version is not provided. I've tested both cases, providing and not providing the version, for the mariadb-server package, in a Vagrant virtual machine with the box `puppetlabs/centos-6.6-64-puppet`, and I have successfully installed the MariaDB server in both cases.

Please, let me know if you still are experiencing this issue (use the `master` branch, not the release `1.0.0`). If so, please, paste attach your manifest(s) to exactly reproduce your case.
